project:
  type: website
  resources:
    - qr/**
    - imagens/qrcode_**
    - contato.vcf

website:
  title: "Projeto Dourados"

languages:
  pt:
    name: Português
    dir: pt
    default: true
  en:
    name: English
    dir: en

format:
  html:
    toc: true
    number-sections: false
    include-in-header: header.html
    theme: 
      light:
        - styles.scss
        - theme-light.scss
      dark:
        - darkly 
        - styles.scss
        - theme-dark.scss
    fontsize: 1.1em
    linestretch: 1.4
    number-depth: 3

bibliography: dourados.bib
